//! Backing — where a buffer's bytes live, and the sync discipline that
//! makes concurrent editors of the same file safe (design rev 4: the
//! backing file IS a peer).
//!
//! `Backing` is the four-case authority: a local path, a remote path
//! over a persistent shell, a tool (content regenerated by a plugin
//! peer), or nothing (scratch). `Sync` is the engine shared by the two
//! file-shaped cases: a Document peer whose replica always mirrors the
//! last-known disk content.
//!
//! The invariants:
//! - The mirror replica's text equals the disk content identified by
//!   `token` (an opaque content token — `ShellFs.hashToken` remotely,
//!   sha256 locally).
//! - The mirror is NEVER pulled to head (`peerSnapshot` is off-limits):
//!   an external disk change is diffed against the mirror and committed
//!   as the mirror's own ops, so the CRDT transforms it against unsaved
//!   local work — nvim's `:w` merges like a remote collaborator.
//! - A save writes the buffer at a version `Vs` with a *guarded*
//!   test-and-set (only if the disk still matches `token`); on success
//!   the mirror advances to exactly `Vs` (`peerSyncTo` — not head,
//!   which may already contain post-save typing). On `error.Stale`,
//!   merge the disk first, then retry.
//!
//! The diff is prefix/suffix trimming — one replaced window. Correct
//! always (both sides converge on the disk content); coarser than a
//! structural diff when an external writer edits two distant regions
//! (the window spans both). A refinement ladder (line-based Myers
//! inside the window) exists if that coarseness ever bites; anchors
//! inside the replaced window collapse to its edge either way.

const std = @import("std");
const Allocator = std.mem.Allocator;
const assert = std.debug.assert;

const stemma = @import("stemma");
const Document = @import("Document.zig");
const ShellFs = @import("ShellFs.zig");

/// Where a buffer's bytes live. The authority, not just a path.
pub const Backing = union(enum) {
    /// Scratch: no authority, no save.
    none,
    /// A local file (task-pool atomic writes).
    file: struct { path: []u8, sync: Sync },
    /// A remote file over a persistent shell (coreutils tier).
    shell: struct { fs: *ShellFs, path: []u8, sync: Sync },
    /// Content regenerated by the named plugin peer (magit-class);
    /// refresh is that peer committing — no sync engine, no save
    /// unless the tool defines one.
    tool: struct { name: []u8 },
};

/// The backing peer: mirror of the last-known disk content.
pub const Sync = struct {
    peer: Document.PeerId,
    /// Opaque content token of the disk state the mirror reflects
    /// (null until the first load/save). Compared for equality only.
    token: ?[]u8 = null,

    pub const peer_name = "backing.fs";

    pub fn init(gpa: Allocator, doc: *Document) Document.AddPeerError!Sync {
        return .{ .peer = try doc.addPeer(gpa, peer_name) };
    }

    pub fn deinit(self: *Sync, gpa: Allocator, doc: *Document) void {
        if (self.token) |tk| gpa.free(tk);
        doc.removePeer(gpa, self.peer);
        self.* = undefined;
    }

    /// Initial load into an empty document: the disk content arrives as
    /// the mirror's insert (a mutation by the filesystem, not the user —
    /// not undoable), and the mirror is exactly the disk.
    pub fn load(self: *Sync, gpa: Allocator, doc: *Document, bytes: []const u8, token: []const u8) Allocator.Error!void {
        assert(doc.peerText(self.peer).isEmpty());
        if (bytes.len > 0) {
            try doc.peerInsert(gpa, self.peer, 0, bytes);
            _ = try doc.peerCommit(gpa, self.peer);
        }
        try self.setToken(gpa, token);
    }

    /// Adopt an already base-loaded document (bulk load: the content IS
    /// the compacted base, zero events — see `Document.adoptContent`).
    /// The mirror peer bootstraps from the base, so it equals the disk
    /// without any insert.
    pub fn loadBased(self: *Sync, gpa: Allocator, doc: *Document, token: []const u8) Allocator.Error!void {
        assert(doc.peerText(self.peer).eql(doc.text().*));
        try self.setToken(gpa, token);
    }

    /// An external writer changed the disk: commit the difference as
    /// the mirror's ops (merges into the buffer like a remote
    /// collaborator's edits) and adopt the new token. Returns whether
    /// the buffer changed.
    pub fn mergeExternal(self: *Sync, gpa: Allocator, doc: *Document, new_bytes: []const u8, token: []const u8) Allocator.Error!bool {
        const mirror = doc.peerText(self.peer);
        const old_bytes = try ropeBytes(gpa, mirror);
        defer gpa.free(old_bytes);
        const changed = if (diffWindow(old_bytes, new_bytes)) |w| blk: {
            if (w.old_end > w.start) {
                try doc.peerDelete(gpa, self.peer, .{ .start = w.start, .end = w.old_end });
            }
            if (w.new_end > w.start) {
                try doc.peerInsert(gpa, self.peer, w.start, new_bytes[w.start..w.new_end]);
            }
            break :blk try doc.peerCommit(gpa, self.peer);
        } else false;
        try self.setToken(gpa, token);
        return changed;
    }

    /// A guarded save of version `saved_version` landed: the disk now
    /// holds exactly that version's content. Advance the mirror to it —
    /// not to head, which may already contain post-save typing.
    pub fn markSaved(self: *Sync, gpa: Allocator, doc: *Document, saved_version: []const u8, token: []const u8) Allocator.Error!void {
        try doc.peerSyncTo(gpa, self.peer, saved_version);
        try self.setToken(gpa, token);
    }

    fn setToken(self: *Sync, gpa: Allocator, token: []const u8) Allocator.Error!void {
        const dup = try gpa.dupe(u8, token);
        if (self.token) |old| gpa.free(old);
        self.token = dup;
    }
};

/// Content token for local files: sha256 hex — same equality-only
/// contract as `ShellFs.hashToken`, computed on bytes we already hold.
pub fn localToken(bytes: []const u8) [64]u8 {
    var digest: [32]u8 = undefined;
    std.crypto.hash.sha2.Sha256.hash(bytes, &digest, .{});
    var hex: [64]u8 = undefined;
    for (digest, 0..) |b, i| {
        _ = std.fmt.bufPrint(hex[i * 2 ..][0..2], "{x:0>2}", .{b}) catch unreachable;
    }
    return hex;
}

/// `old[start..old_end)` became `new[start..new_end)`.
const Window = struct { start: usize, old_end: usize, new_end: usize };

/// The single replaced window between two byte strings, snapped to
/// UTF-8 boundaries. Null when equal.
fn diffWindow(old: []const u8, new: []const u8) ?Window {
    if (std.mem.eql(u8, old, new)) return null;
    const max_prefix = @min(old.len, new.len);
    var p: usize = 0;
    while (p < max_prefix and old[p] == new[p]) p += 1;
    while (p > 0 and p < old.len and old[p] & 0xC0 == 0x80) p -= 1;
    var s: usize = 0;
    const max_suffix = @min(old.len, new.len) - p;
    while (s < max_suffix and old[old.len - 1 - s] == new[new.len - 1 - s]) s += 1;
    while (s > 0 and old[old.len - s] & 0xC0 == 0x80) s -= 1;
    return .{ .start = p, .old_end = old.len - s, .new_end = new.len - s };
}

fn ropeBytes(gpa: Allocator, rope: *const stemma.Rope) Allocator.Error![]u8 {
    var snap = rope.snapshot();
    defer snap.deinit(gpa);
    return snap.toOwnedSlice(gpa);
}

// ── Tests ───────────────────────────────────────────────────────────
// The concurrency scenarios from design rev 4, end to end through a
// real file and a real /bin/sh: weft + external writer (the nvim
// case), and two unconnected wefts converging through the disk.

const t = std.testing;

fn shellEnviron() std.process.Environ {
    return .{ .block = .{ .slice = std.mem.span(std.c.environ) } };
}

fn docBytes(gpa: Allocator, doc: *const Document) ![]u8 {
    return ropeBytes(gpa, doc.text());
}

test "diffWindow: trims, snaps to scalar boundaries" {
    try t.expectEqual(@as(?Window, null), diffWindow("abc", "abc"));
    const w = diffWindow("hello world", "hello brave world").?;
    try t.expectEqual(@as(usize, 6), w.start);
    try t.expectEqual(@as(usize, 6), w.old_end);
    try t.expectEqual(@as(usize, 12), w.new_end);
    // Multi-byte: the changed byte sits inside a codepoint; the window
    // must widen to whole scalars.
    const w2 = diffWindow("aàb", "aèb").?; // à=0xC3A0 è=0xC3A8 share 0xC3
    try t.expectEqual(@as(usize, 1), w2.start);
    try t.expectEqual(@as(usize, 3), w2.old_end);
    try t.expectEqual(@as(usize, 3), w2.new_end);
}

test "backing: external write merges with unsaved local edits (the nvim case)" {
    const gpa = t.allocator;
    var doc = try Document.init(gpa, "user");
    defer doc.deinit(gpa);
    var sync = try Sync.init(gpa, &doc);
    defer sync.deinit(gpa, &doc);

    const disk0 = "line one\nline two\nline three\n";
    const tk0 = localToken(disk0);
    try sync.load(gpa, &doc, disk0, &tk0);

    // Local unsaved edit at the top…
    try doc.insert(gpa, 0, "LOCAL ");
    // …while "nvim" rewrites line three on disk.
    const disk1 = "line one\nline two\nline 3!\n";
    const tk1 = localToken(disk1);
    try t.expect(try sync.mergeExternal(gpa, &doc, disk1, &tk1));

    const merged = try docBytes(gpa, &doc);
    defer gpa.free(merged);
    try t.expectEqualStrings("LOCAL line one\nline two\nline 3!\n", merged);

    // A second identical poll is a no-op.
    try t.expect(!try sync.mergeExternal(gpa, &doc, disk1, &tk1));
}

test "backing: save advances the mirror to the saved version, not head" {
    const gpa = t.allocator;
    var doc = try Document.init(gpa, "user");
    defer doc.deinit(gpa);
    var sync = try Sync.init(gpa, &doc);
    defer sync.deinit(gpa, &doc);
    const tk0 = localToken("base");
    try sync.load(gpa, &doc, "base", &tk0);

    try doc.insert(gpa, 4, " saved");
    const saved_version = try doc.version(gpa);
    defer gpa.free(saved_version);
    const saved_bytes = try docBytes(gpa, &doc);
    defer gpa.free(saved_bytes);
    // Post-save typing lands before the save completes.
    try doc.insert(gpa, 0, "unsaved ");

    const tk1 = localToken(saved_bytes);
    try sync.markSaved(gpa, &doc, saved_version, &tk1);
    // Mirror == what the disk holds (the saved version), not the head.
    const mirror = try ropeBytes(gpa, doc.peerText(sync.peer));
    defer gpa.free(mirror);
    try t.expectEqualStrings("base saved", mirror);

    // The next external change diffs against the *saved* state, so our
    // own saved edits are not re-imported as someone else's.
    const disk2 = "base saved externally\n";
    const tk2 = localToken(disk2);
    _ = try sync.mergeExternal(gpa, &doc, disk2, &tk2);
    const merged = try docBytes(gpa, &doc);
    defer gpa.free(merged);
    try t.expectEqualStrings("unsaved base saved externally\n", merged);
}

test "backing: two unconnected editors converge through one file over /bin/sh" {
    const gpa = t.allocator;
    var tmp_dir = t.tmpDir(.{});
    defer tmp_dir.cleanup();
    const path = try std.fmt.allocPrint(gpa, ".zig-cache/tmp/{s}/shared.txt", .{tmp_dir.sub_path});
    defer gpa.free(path);

    var fs = try ShellFs.spawn(gpa, &.{"/bin/sh"}, shellEnviron());
    defer fs.deinit();

    // Editor A creates the file.
    var a = try Document.init(gpa, "alice");
    defer a.deinit(gpa);
    var sa = try Sync.init(gpa, &a);
    defer sa.deinit(gpa, &a);
    try a.insert(gpa, 0, "alpha\nomega\n");
    {
        const av = try a.version(gpa);
        defer gpa.free(av);
        const bytes = try docBytes(gpa, &a);
        defer gpa.free(bytes);
        const tk = try fs.writeGuarded(gpa, path, bytes, null);
        defer gpa.free(tk);
        try sa.markSaved(gpa, &a, av, tk);
    }

    // Editor B opens the same file (no wire between A and B).
    var b = try Document.init(gpa, "bob");
    defer b.deinit(gpa);
    var sb = try Sync.init(gpa, &b);
    defer sb.deinit(gpa, &b);
    {
        const bytes = try fs.readAll(gpa, path);
        defer gpa.free(bytes);
        const tk = try fs.hashToken(gpa, path);
        defer gpa.free(tk);
        try sb.load(gpa, &b, bytes, tk);
    }

    // Both edit different regions; A saves first.
    try a.insert(gpa, 0, "A: ");
    try b.insert(gpa, b.text().byteLen(), "B was here\n");
    {
        const av = try a.version(gpa);
        defer gpa.free(av);
        const bytes = try docBytes(gpa, &a);
        defer gpa.free(bytes);
        const tk = try fs.writeGuarded(gpa, path, bytes, sa.token.?);
        defer gpa.free(tk);
        try sa.markSaved(gpa, &a, av, tk);
    }

    // B's guarded save is stale — merge the disk, then retry: nothing lost.
    {
        const bv = try b.version(gpa);
        defer gpa.free(bv);
        const bytes = try docBytes(gpa, &b);
        defer gpa.free(bytes);
        try t.expectError(error.Stale, fs.writeGuarded(gpa, path, bytes, sb.token.?));

        const disk = try fs.readAll(gpa, path);
        defer gpa.free(disk);
        const tk = try fs.hashToken(gpa, path);
        defer gpa.free(tk);
        _ = try sb.mergeExternal(gpa, &b, disk, tk);
        const merged = try docBytes(gpa, &b);
        defer gpa.free(merged);
        const bv2 = try b.version(gpa);
        defer gpa.free(bv2);
        const tk2 = try fs.writeGuarded(gpa, path, merged, sb.token.?);
        defer gpa.free(tk2);
        try sb.markSaved(gpa, &b, bv2, tk2);
    }

    // A polls, merges B's save: both editors and the disk agree, and
    // both editors' contributions survived.
    {
        const disk = try fs.readAll(gpa, path);
        defer gpa.free(disk);
        const tk = try fs.hashToken(gpa, path);
        defer gpa.free(tk);
        _ = try sa.mergeExternal(gpa, &a, disk, tk);
        const a_text = try docBytes(gpa, &a);
        defer gpa.free(a_text);
        const b_text = try docBytes(gpa, &b);
        defer gpa.free(b_text);
        try t.expectEqualStrings(b_text, a_text);
        try t.expect(std.mem.indexOf(u8, a_text, "A: ") != null);
        try t.expect(std.mem.indexOf(u8, a_text, "B was here") != null);
    }
}
